// src/config/trialBonuses.ts

export const DOJO_BONUSES: Record<number | string, string[]> = {
  1: ['Combat', '+3 to Dice Roll'],
  2: ['Shuriken', 'Reroll 1 Die'],
  3: ['Stealth', 'Swap D20 for D12'],
  4: ['Disguise', 'Swap D12 for D10'],
  5: ['Climbing', 'Swap D10 for D8'],
  6: ['Arcane', '+1 To Dice Roll'],
  7: ['Combat', '-3 to Dice Roll'],
  8: ['Shuriken', 'Change 1 Dice outcome to 1'],
  9: ['Stealth', 'Swap D10 for D12'],
  10: ['Disguise', 'Swap D8 for D10'],
  11: ['Climbing', 'Swap D6 for D8'],
  12: ['Arcane', '-1 to Dice Roll'],
  13: ['Combat', '+2 to Dice Roll'],
  14: ['Shuriken', '+2 to Dice Roll'],
  15: ['Stealth', 'Reroll 1 Die'],
  16: ['Disguise', 'Every Round: +2 to Dice Roll'],
  17: ['Climbing', 'Every Round: +1 to Dice Roll'],
  18: ['Arcane', 'Every Round: +2 to Dice Roll'],
  19: ['Ninja Stuff', 'Reroll 1 Die'],
  20: ['Combat', 'Reroll 1 Die'],
  21: ['Shuriken', 'Reroll 1 Die'],
  22: ['Stealth', 'Reroll 1 Die'],
  23: ['Disguise', 'Reroll 1 Die'],
  24: ['Climbing', 'Reroll 1 Die'],
  25: ['Arcane', 'Reroll 1 Die'],
  26: ['Combat', 'Reroll 1 Die'],
  27: ['Shuriken', 'Reroll 1 Die'],
  28: ['Stealth', 'Reroll 1 Die'],
  29: ['Disguise', 'Reroll 1 Die'],
  30: ['Climbing', 'Reroll 1 Die'],
  31: ['Arcane', 'Reroll 1 Die'],
  32: ['Combat', 'Add a D4 to your Dice Roll'],
  33: ['Shuriken', 'Add a D4 to your Dice Roll'],
  34: ['Stealth', 'Add a D4 to your Dice Roll'],
  35: ['Disguise', '+2 to Dice Roll'],
  36: ['Climbing', '+2 to Dice Roll'],
  37: ['Arcane', '+2 to Dice Roll'],
  38: ['Combat', 'Every Round: +2 to Dice Roll'],
  39: ['Shuriken', 'Every Round: -2 to Dice Roll'],
  40: ['Stealth', 'Every Round: +2 to Dice Roll'],
  41: ['Disguise', 'Every Round: -2 to Dice Roll'],
  42: ['Climbing', 'Every Round: +2 to Dice Roll'],
  43: ['Arcane', 'Every Round: -2 to Dice Roll'],
  44: ['Disguise', 'Reroll 1 Die'],
  45: ['Shuriken', 'Reroll 1 Die'],
  46: ['Ninja Stuff', 'Reroll 1 Die'],
  47: ['Ninja Stuff', 'Reroll 1 Die'],
  48: ['Ninja Stuff', 'Reroll 1 Die'],
  49: ['Ninja Stuff', 'Reroll 1 Die'],
  50: ['Ninja Stuff', 'Reroll 1 Die'],
  51: ['Ninja Stuff', 'Reroll 1 Die'],
  52: ['Ninja Stuff', 'Reroll 1 Die'],
  53: ['Ninja Stuff', 'Reroll 1 Die'],
  54: ['Ninja Stuff', 'Reroll 1 Die'],
  55: ['Disguise', 'Reroll 1 Die'],
  56: ['Ninja Stuff', 'Reroll 1 Die'],
  57: ['Combat', '+2 to Dice Roll'],
  58: ['Shuriken', '+2 to Dice Roll'],
  59: ['Stealth', '+2 to Dice Roll'],
  60: ['Disguise', '+2 to Dice Roll'],
  61: ['Climbing', '+2 to Dice Roll'],
  62: ['Arcane', '+2 to Dice Roll'],
  63: ['Ninja Stuff', '+2 to Dice Roll'],
  64: ['Combat', 'Every Round: +2 to Dice Roll'],
  65: ['Shuriken', 'Every Round: -2 to Dice Roll'],
  66: ['Stealth', 'Every Round: +2 to Dice Roll'],
  67: ['Disguise', 'Every Round: -2 to Dice Roll'],
  68: ['Climbing', 'Every Round: +2 to Dice Roll'],
  69: ['Arcane', 'Every Round: -2 to Dice Roll'],
  B1: ['Combat', '+2 to your Dice Roll Every Round '],
  B2: ['Shuriken', '+2 to your Dice Roll Every Round '],
  B3: ['Stealth', '+2 to your Dice Roll Every Round '],
  B4: ['Disguise', '+2 to your Dice Roll Every Round '],
  B5: ['Climbing', '+2 to your Dice Roll Every Round '],
  B6: ['Arcane', 'Every Round: +2 to Dice Roll'],
  B7: ['Ninja Stuff', 'Every Round: +2 to Dice Roll'],
  B8: ['Combat', '+2 to your Dice Roll Every Round '],
  B9: ['Shuriken', '+2 to your Dice Roll Every Round '],
  B10: ['Stealth', '+2 to your Dice Roll Every Round '],
  B11: ['Disguise', '+2 to your Dice Roll Every Round '],
  B12: ['Climbing', '+2 to your Dice Roll Every Round '],
  B13: ['Arcane', 'Every Round: +2 to Dice Roll'],
}; 
